### PR TITLE
MK - FLAG-23 - issue resolved for SQL criteria. User can provide dynamic message for SQL Criteria

### PR DESCRIPTION
**Pull request by maimoonak**
MK - FLAG-23 - issue resolved for SQL criteria. When user chooses SQL he can specify dynamically the column number to replace in message like '${indexToReplace}'

### CODE REVIEW

**Comment by mogoodrich** [comment]
Ack... @maimoonak do you know if you are making changes to line endings and/or indentations when making your commits?  If you look at the files changed diff (https://github.com/openmrs/openmrs-module-patientflags/pull/1/files), for each file you have touched, it shows the entire file has having been changed, making it impossible for me to review!  Take a look...

**Comment by maimoonak** [comment]
Not sure what has happened with the commit. I have not tried formatting anything in the code. What do you suggest?

**Comment by djazayeri** [comment]
Maybe doing this will help?
https://help.github.com/articles/dealing-with-line-endings

I think you might have to re-copy your changes into a new clone of the repo
after doing this...

-Darius

**Comment by maimoonak** [comment]
Thanks @djazayeri . Seems that it would resolve the issue. @mogoodrich apologies for the inconvenience, I would resubmit a pull request after applying changes to module.

**Comment by maimoonak** [comment]
Submitted another pull request with readable commits

**Pull request closed without merging**
