### PR TITLE
FLAG-71: Upgrade to java 8

### PR DESCRIPTION
**Pull request by ManojLL**
### Description of what I change
changed java version 1.6 to 1.8

Issue work on : [FLAG-71](https://openmrs.atlassian.net/jira/software/c/projects/FLAG/list?selectedIssue=FLAG-71)

[FLAG-71]: https://openmrs.atlassian.net/browse/FLAG-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by wikumChamith — APPROVED** [review]

**Comment by wikumChamith** [comment]
@dkayiwa can we merge this?

**Comment by dkayiwa** [comment]
@wikumChamith you are free to make that decision 😊

**Comment by wikumChamith** [comment]
> @wikumChamith you are free to make that decision 😊

I just wanted to get your approval :sweat_smile:

**Comment by dkayiwa** [comment]
> I just wanted to get your approval

You are the primary mentor for this project. 😊

**Comment by wikumChamith** [comment]
> > I just wanted to get your approval
> 
> You are the primary mentor for this project. 😊

It is always better to get a second opinion :blush:

**Pull request merged**
