### PR TITLE
PLAT-38: Add Platform 2.x compatibility to Patient Flags module

### PR DESCRIPTION
**Pull request by tendomatGitHub**
https://issues.openmrs.org/browse/PLAT-38

@djazayeri  , @dkayiwa i added platform 2.x compatibility.It was missed out

### CODE REVIEW

**Comment by dkayiwa** [comment]
The ticket status says you are still doing more work on this.

**Comment by dkayiwa** [comment]
Did you just make this change and commit, or did you even compile and test to confirm all is well?

**Comment by tendomatGitHub** [comment]
@dkayiwa  yes i did compile and test,and it works fine.

@djazayeri  true,but previously after loading the omod,it could not start ,and the red flag was "Module failed to start .It requires Logic " module

**Comment by tendomatGitHub** [comment]
@dkayiwa  working on releasing  patient Flags then have the ticket closed.

**Comment by dkayiwa** [comment]
Can you squash these commits into one?

**Comment by tendomatGitHub** [comment]
@dkayiwa  the last commit was on master aimed at preparing Patient Flags for release.

**Comment by dkayiwa** [comment]
Does it belong to your pull request?

**Comment by dkayiwa** [comment]
Can you take a look at this in regards to squashing commits into one? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by tendomatGitHub** [comment]
Yes i quess there was some mix up.Let me fix this.

**Pull request closed without merging**
