### PR TITLE
FLAG-67: Fix rendering of flags via simple objects that is currently broken in platform version greater than 2.5.*

### PR DESCRIPTION
**Pull request by slubwama**
# Description of what I changed 

1. I added a key for the patient flags object returned to the UI via a simple object in the PatientflagsDashboardFragmentController 

# Issues I worked on 

https://issues.openmrs.org/browse/FLAG-67

### CODE REVIEW

**Comment by dkayiwa** [comment]
How is does this failure look like? And how exactly does one reproduce it? Do you have a screenshot?

**Comment by slubwama** [comment]
> How is does this failure look like? And how exactly does one reproduce it? Do you have a screenshot?


Uploading Screen Recording 2024-04-09 at 22.20.43.mov…

@dkayiwa check recording

**Comment by slubwama** [comment]
> How is does this failure look like? And how exactly does one reproduce it? Do you have a screenshot?

It happens when a flag is being loaded on the UI of the patient dashboard in 2.x coreapps.

**Comment by dkayiwa** [comment]
Will this work in platform versions below 2.5?

**Comment by ManojLL** [comment]
@slubwama 

When adding priority, we include flags with display styles using the [style tag](https://openmrs.atlassian.net/wiki/spaces/docs/pages/25467777/Patient+Flags+Module#:~:text=style%20property%20to%3A-,style%3D%22color%3Ared%22,-Flags%20can%20also). Therefore, we need to remove the style tag from the following line of code in `PatientflagsDashboardFragmentController` class. 
`flagsString.append("<li><span style='").append(flag.getPriority().getStyle()).append("'>").append(flag.evalMessage(patient.getPatientId())).append("</span></li>");`

**Comment by ManojLL** [comment]
I’m taking over this ticket because it’s related to my GSoC project. 

 PR: https://github.com/openmrs/openmrs-module-patientflags/pull/77

**Comment by wikumChamith** [comment]
Merged At: https://github.com/openmrs/openmrs-module-patientflags/commit/7e254888debacfbaa4fcb3e7a09d7b116ffb708a

Thank you @slubwama for the effort.

**Pull request closed without merging**
