### PR TITLE
WIP: Flag-33

### PR DESCRIPTION
**Pull request by maimoonak**
https://issues.openmrs.org/browse/FLAG-33

### CODE REVIEW

**Comment by dkayiwa** [comment]
It would be great to include the pull request url.

**Comment by dkayiwa** [comment]
@maimoonak are you still working on this?

**Comment by maimoonak** [comment]
Yeh. There is some final work remaining for one REST resource.

**Comment by dkayiwa** [comment]
@maimoonak do you mind claiming the ticket? 😊

**Comment by dkayiwa** [comment]
Closing because of merge conflicts.

**Pull request closed without merging**
