### PR TITLE
FLAG-39 OWA - Setup OWA in existing module

### PR DESCRIPTION
**Pull request by ynurmahomed**
https://issues.openmrs.org/browse/FLAG-39

### CODE REVIEW

**Comment by ssmusoke** [comment]
@ynurmahomed did you see the Travis failure. Also squash the commits following t https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by ynurmahomed** [comment]
@ssmusoke I've seen the Travis failure. Looks like there is a problem [starting chrome](https://travis-ci.org/openmrs/openmrs-module-patientflags/builds/317383947#L2130), have no idea why. I will create a new PR after sorting out the issue.

**Comment by ssmusoke** [comment]
@ynurmahomed Please can you squash the commits in this PR

**Comment by ynurmahomed** [comment]
@ssmusoke please consider PR https://github.com/openmrs/openmrs-module-patientflags/pull/20.

**Pull request closed without merging**
