### PR TITLE
FLAG-39: OWA - Setup OWA in existing module

### PR DESCRIPTION
**Pull request by ynurmahomed**
https://issues.openmrs.org/browse/FLAG-39

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ynurmahomed are you still working on this?

**Comment by ynurmahomed** [comment]
@dkayiwa No, its finished. Tests are not running on travis but run fine on local environment.

**Comment by dkayiwa** [comment]
@cintiadr do you have any idea why this fails here and also on bamboo? https://ci.openmrs.org/browse/FLAG-FLAG-4/log

It works fine locally.

**Comment by cintiadr** [comment]
build	09-Jan-2018 14:20:52	[INFO] > patientflags@0.1.0 test /home/bamboo-agent/bamboo-agent/xml-data/build-dir/FLAG-FLAG-JOB1/owa
build	09-Jan-2018 14:20:52	[INFO] > karma start --singleRun=true
build	09-Jan-2018 14:20:52	[INFO] 
build	09-Jan-2018 14:20:55	[INFO] [32m09 01 2018 14:20:55.972:INFO [karma]: [39mKarma v1.7.1 server started at http://0.0.0.0:9876/
build	09-Jan-2018 14:20:55	[INFO] [32m09 01 2018 14:20:55.974:INFO [launcher]: [39mLaunching browser Chrome with unlimited concurrency
build	09-Jan-2018 14:20:56	[INFO] [32m09 01 2018 14:20:56.045:INFO [launcher]: [39mStarting browser Chrome
build	09-Jan-2018 14:20:56	[INFO] [31m09 01 2018 14:20:56.046:ERROR [launcher]: [39mNo binary for Chrome browser on your platform.
build	09-Jan-2018 14:20:56	[INFO]   Please, set "CHROME_BIN" env variable.


While I installed 'chromium-browser','firefox' and 'xvfb', I don't think it has been used. Instead, I believe saucelabs are being used for end-to-end tests with browsers. 

To run tests with browsers is always very complicated.

**Comment by cintiadr** [comment]
You usually have to setup xvfb (remember, these servers don't have X, so you need to create virtual displays. And I'm not even sure what's the status or how they've been updated.

**Comment by dkayiwa** [comment]
So would you recommend that we simply disable such tests?

**Comment by ynurmahomed** [comment]
Maybe we can try running with ```ChromeHeadless```:

https://github.com/openmrs/openmrs-module-patientflags/blob/master/owa/karma.conf.js#L98

**Comment by dkayiwa** [comment]
Can you try it out?

**Comment by ynurmahomed** [comment]
OK. I'll try to run a build of my branch with Travis.

**Comment by ynurmahomed** [comment]
@dkayiwa looks like it worked.

https://travis-ci.org/ynurmahomed/openmrs-module-patientflags/builds/327223707

**Comment by dkayiwa** [comment]
@ynurmahomed are you doing a pull request?

**Comment by dkayiwa** [comment]
@ynurmahomed travis is happy. But bamboo is not yet https://ci.openmrs.org/download/FLAG-FLAG-JOB1/build_logs/FLAG-FLAG-JOB1-5.log

**Comment by ynurmahomed** [comment]
@dkayiwa travis is failing again :cry:. Is chrome installed on bamboo?

    build	11-Jan-2018 21:34:53	[INFO] [31m11 01 2018 21:34:53.146:ERROR [launcher]: [39mNo binary for ChromeHeadless browser on your platform.

**Pull request merged**
